# This module tries to find the LHAPDF installation on your system.
# Copied from https://github.com/yhaddad/Fasilico/blob/master/cmake/FindLHAPDF.cmake
# Modified by P. Sznajder

# try to find LHAPDF in user defined path
FIND_LIBRARY(LHAPDF_LIBRARIES
  NAMES
  LHAPDF
  PATHS
  ${LHAPDF_PREFIX}/lib
  )


# if not try to find LHAPDF in standard instalation paths
IF(${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND")
  FIND_LIBRARY(LHAPDF_LIBRARIES
    NAMES
    LHAPDF
    PATHS
    /usr/lib
    /usr/local/lib
    )
ENDIF(${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND")

# if not found try to use lhapdf-config tool
IF(${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND")
  FIND_PROGRAM(LHAPDF_CONFIG_EXECUTABLE NAMES lhapdf-config)
  IF(${LHAPDF_CONFIG_EXECUTABLE} MATCHES "LHAPDF_CONFIG_EXECUTABLE-NOTFOUND")
    MESSAGE(STATUS "Looking for LHAPDF... - lhapdf-config executable not found")
  ELSE(${LHAPDF_CONFIG_EXECUTABLE} MATCHES "LHAPDF_CONFIG_EXECUTABLE-NOTFOUND")
    MESSAGE(STATUS "Looking for LHAPDF... - using lhapdf-config executable")
    EXEC_PROGRAM(${LHAPDF_CONFIG_EXECUTABLE} ARGS "--prefix" OUTPUT_VARIABLE LHAPDF_PREFIX)
    FIND_LIBRARY(LHAPDF_LIBRARIES
      NAMES
      LHAPDF
      PATHS
      ${LHAPDF_PREFIX}/lib
      )
  ENDIF(${LHAPDF_CONFIG_EXECUTABLE} MATCHES "LHAPDF_CONFIG_EXECUTABLE-NOTFOUND")
ENDIF(${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND")

IF(NOT ${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND")
  FIND_PATH(LHAPDF_INCLUDE_DIR
    LHAPDF/LHAPDF.h
    /usr/include
    /usr/local/include
    ${LHAPDF_PREFIX}/include
    )
ENDIF(NOT ${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND")

# final printout.
IF((${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND") OR (${LHAPDF_INCLUDE_DIR} MATCHES "LHAPDF_INCLUDE_DIR-NOTFOUND"))
  MESSAGE( FATAL_ERROR "Could NOT find LHAPDF")
ELSE((${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND") OR (${LHAPDF_INCLUDE_DIR} MATCHES "LHAPDF_INCLUDE_DIR-NOTFOUND"))
  MESSAGE(STATUS "Found LHAPDF library as ${LHAPDF_LIBRARIES}" )
  MESSAGE(STATUS "Found LHAPDF headers in ${LHAPDF_INCLUDE_DIR}" )
  include_directories(${LHAPDF_INCLUDE_DIR})
ENDIF((${LHAPDF_LIBRARIES} MATCHES "LHAPDF_LIBRARIES-NOTFOUND") OR (${LHAPDF_INCLUDE_DIR} MATCHES "LHAPDF_INCLUDE_DIR-NOTFOUND"))
